---
- name: install pip packages
  pip:
    name:
    - boto
    - botocore
    - boto3
    - awscli
    - cfn_flip
    state: latest

- name: Install "aws-azure-login" package
  npm:
    name: aws-azure-login
    global: yes
    unsafe_perm: yes
    state: present

- name: Install "serverless" package
  npm:
    name: serverless
    global: yes
    unsafe_perm: yes
    state: present

- name: Install aws-iam-authenticator
  get_url:
    url: "https://s3.us-west-2.amazonaws.com/amazon-eks/{{ AWS_IAM_AUTHENTICATOR_VERSION }}/2021-07-05/bin/linux/amd64/aws-iam-authenticator"
    checksum: "sha256:https://s3.us-west-2.amazonaws.com/amazon-eks/{{ AWS_IAM_AUTHENTICATOR_VERSION }}/2021-07-05/bin/linux/amd64/aws-iam-authenticator.sha256"
    dest: /usr/local/bin/aws-iam-authenticator
    mode: 0755
    owner: root
    group: root

- name: Install Session Manager plugin
  apt:
    deb: "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb"
    state: present
