---
- name: Add an apt key for google repository
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7721F63BD38B4796

- name: Add google repository
  apt_repository:
    repo: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
    filename: google-chrome

- name: Install packages
  apt:
    name: "google-chrome-stable"
    state: latest
    update_cache: true
