---
- hosts: all
  become: True
  become_method: sudo
  become_user: root
  roles:
    - {role: common, tags: common}
    - {role: node, tags: node}
    - {role: aws-cli, tags: aws-cli}
    - {role: aws-vpn-client, tags: aws-vpn-client}
    - {role: monitoring, tags: monitoring}
    - {role: google-chrome, tags: google-chrome}
    - {role: docker, tags: docker}
    # Disable till DEB-package is build for Ubuntu 24.04
    # https://dev.mysql.com/downloads/workbench/
    # - {role: mysql-client, tags: mysql-client}
    - {role: terraform, tags: terraform}
    - {role: terragrunt, tags: terragrunt}
    - {role: sops, tags: sops}
    - {role: vault, tags: vault}
    - {role: kubernetes, tags: kubernetes}
    - {role: packer, tags: packer}
    - {role: onepassword, tags: onepassword}
