---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  roles:
    - {role: common, tags: common}
    - {role: monitoring, tags: monitoring}
    - {role: google-chrome, tags: google-chrome}
    - {role: docker, tags: docker}
    - {role: mysql-client, tags: mysql-client}
    - {role: virtualbox, tags: virtualbox}
    - {role: vagrant, tags: vagrant}
    - {role: terraform, tags: terraform}
    - {role: terragrunt, tags: terragrunt}
    - {role: kubernetes, tags: kubernetes}
    - {role: packer, tags: packer}
    - {role: travis, tags: travis}
    - {role: atom, tags: atom}
