---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  roles:
    - {role: common, tags: common}
    - mysql-client
    - docker
    - {role: google-chrome, tags: google-chrome}
    - {role: virtualbox, tags: virtualbox}
    - {role: hipchat, tags: hipchat}
    - atom
