---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  roles:
    - {role: common, tags: common}
    - {role: google-chrome, tags: google-chrome}
    - {role: docker, tags: docker}
    - {role: mysql-client, tags: mysql-client}
    - {role: virtualbox, tags: virtualbox}
    - {role: vagrant, tags: vagrant}
    - {role: atom, tags: atom}
