---

- name: Fix aws vpn client config
  ansible.builtin.copy:
    src: "files/runtime.json"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: u=rw,g=rw,o=r
  loop:
    - "/opt/awsvpnclient/AWS VPN Client.runtimeconfig.json"
    - "/opt/awsvpnclient/Service/ACVC.GTK.Service.runtimeconfig.json"
  notify: Restart awsvpnclient service

- name: Fix aws vpn client desktop link
  ansible.builtin.lineinfile:
    path: /usr/share/applications/awsvpnclient.desktop
    regexp: '^Exec='
    line: Exec=/opt/awsvpnclient/AWS\\ VPN\\ Client %u
