---
- name: Add AWS VPN client repository key
  apt_key:
    id: 0B8B890071C04E08
    url: https://d20adtppz83p9s.cloudfront.net/GTK/latest/debian-repo/awsvpnclient_public_key.asc
    state: present

# TODO: unsecure, replace with ppa or backports
# Check for current libssl versions: http://security.ubuntu.com/ubuntu/pool/main/o/openssl/
- name: Add old ssl-library
  apt:
    deb: "http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb"
    state: present

- name: Add AWS VPN client repository
  apt_repository:
    repo: "deb [arch=amd64] https://d20adtppz83p9s.cloudfront.net/GTK/latest/debian-repo ubuntu-20.04 main"
    filename: aws-vpn-client

- name: Install AWS VPN client packages
  apt:
    name: awsvpnclient
    state: latest
    update_cache: True
