---
- name: Add AWS VPN client repository key
  apt_key:
    id: A869E75F05B35B1C0FAAB620219B0B8D707EA7B7
    url: https://d20adtppz83p9s.cloudfront.net/GTK/latest/debian-repo/awsvpnclient_public_key.asc
    state: present

- name: Add AWS VPN client repository
  apt_repository:
    repo: "deb [arch=amd64] https://d20adtppz83p9s.cloudfront.net/GTK/latest/debian-repo ubuntu-18.04 main"
    filename: aws-vpn-client

- name: Install AWS VPN client packages
  apt:
    name: awsvpnclient
    state: latest
    update_cache: true
