---
- name: Install monitoring packages
  ansible.builtin.apt:
    name:
      - lm-sensors
      - psensor
    state: latest
    update_cache: True
    cache_valid_time: 3600
  register: sensor_install
