---
- name: Install monitoring packages
  apt:
    name:
    - lm-sensors
    - hddtemp
    - psensor
    state: latest
    update_cache: true
  register: sensor_install

- name: Detect sensors
  command: sensors-detect
  when: sensor_install is changed