---
- name: Install mysql-client package
  ansible.builtin.apt:
    name:
      - mysql-client
      - mysql-shell
    state: latest
    update_cache: True
    cache_valid_time: 3600

- name: Install DBeaver package
  snap:
    name:
      - dbeaver-ce
    classic: True
    state: present

- name: "Check {{ mysql_bench_package }} is installed"
  command: "dpkg-query -W {{ mysql_bench_package }}"
  register: package_check
  failed_when: package_check.rc > 1
  changed_when: package_check.rc == 1
  ignore_errors: True

- name: "Install {{ mysql_bench_package }} dependencies"
  ansible.builtin.apt:
    name:
      - libatkmm-1.6-1v5
      - libgtkmm-3.0-1t64
      - libmysqlclient21
      - libodbc2
      - libproj25
    state: latest
    update_cache: True
  when: package_check.rc == 1

- name: "Download {{ mysql_bench_package }} package"
  get_url:
    url: "https://cdn.mysql.com//Downloads/MySQLGUITools/{{ mysql_bench_package }}_{{ mysql_bench_version }}-1ubuntu24.04_amd64.deb"
    dest: "/tmp/{{ mysql_bench_package }}_{{ mysql_bench_version }}-1ubuntu24.04_amd64.deb"
    force: True
    owner: root
    group: root
    mode: 0644
  when: package_check.rc == 1

- name: "Install {{ mysql_bench_package }} package"
  ansible.builtin.apt:
    deb: "/tmp/{{ mysql_bench_package }}_{{ mysql_bench_version }}-1ubuntu24.04_amd64.deb"
    update_cache: False
  when: package_check.rc == 1
