---
- name: Install ruby deb packages
  apt:
    name:
      - ruby
      - ruby-dev
    state: latest
    update_cache: True

- name: Install travis-cli gem
  gem:
    name: travis
    state: present
    version: "{{ travis_cli_version }}"
    user_install: False
    include_doc: False
