---
- name: Add required repository for travis
  apt_repository:
    repo: ppa:brightbox/ruby-ng

- name: Install ruby deb packages
  apt:
    name:
    - ruby
    - ruby-dev
    state: latest
    update_cache: true

- name: Install travis-cli gem
  gem:
    name: travis
    state: present
    version: "{{ travis_cli_version }}"
    user_install: no
    include_doc: no
