---

- name: "Check vault is installed"
  shell: "vault --version | grep -qPe '^Vault v{{ vault_version }} .*$'"
  register: version_check
  ignore_errors: True
  changed_when: false

- name: Download vault binary
  get_url:
    url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    dest: "/tmp/vault_{{ vault_version }}_linux_amd64.zip"
  when: version_check is failed

- name: Extract vault
  unarchive:
    remote_src: yes
    src: "/tmp/vault_{{ vault_version }}_linux_amd64.zip"
    dest: "/usr/local/bin"
    owner: root
    group: root
    mode: 0755
  when: version_check is failed