---
- name: Add Oracle vbox 2016 repository key
  apt_key:
    id: 2980AECF
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: Add Oracle vbox repository key
  apt_key:
    id: 98AB5139
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present

- name: Add virtualbox repository
  apt_repository:
    repo: "deb https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    filename: virtualbox

- name: Install virtualbox packages
  apt:
    name: "virtualbox-6.1"
    state: latest
    update_cache: True
