---
- name: Download terrafrom binary
  get_url:
    url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "/tmp/terraform_{{ terraform_version }}_linux_amd64.zip"
    checksum: "sha256:5925cd4d81e7d8f42a0054df2aafd66e2ab7408dbed2bd748f0022cfe592f8d2"

- name: Extract terraform
  unarchive:
    remote_src: yes
    src: "/tmp/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "/usr/local/bin"
    owner: root
    group: root
    mode: 0755
