---

- name: "Check terraform is installed"
  shell: "terraform --version | grep -qPe '^Terraform v{{ terraform_version }}$'"
  register: version_check
  ignore_errors: True
  changed_when: false

- name: Download terrafrom binary
  get_url:
    url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "/tmp/terraform_{{ terraform_version }}_linux_amd64.zip"
  when: version_check is failed

- name: Extract terraform
  unarchive:
    remote_src: yes
    src: "/tmp/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "/usr/local/bin"
    owner: root
    group: root
    mode: 0755
  when: version_check is failed

- name: "Check terraform-docs installed"
  shell: "terraform-docs version | grep -qPe 'version v{{ terraform_docs_version }} '"
  register: docs_version_check
  ignore_errors: True
  changed_when: false

- name: Download terraform-docs binary
  get_url:
    url: "https://terraform-docs.io/dl/v{{ terraform_docs_version }}/terraform-docs-v{{ terraform_docs_version }}-Linux-amd64.tar.gz"
    dest: "/tmp/terraform-docs_{{ terraform_docs_version }}-Linux-amd64.tar.gz"
  when: docs_version_check is failed

- name: Extract terraform-docs
  unarchive:
    remote_src: yes
    src: "/tmp/terraform-docs_{{ terraform_docs_version }}-Linux-amd64.tar.gz"
    dest: "/usr/local/bin"
    owner: root
    group: root
    mode: 0755
  when: docs_version_check is failed
