---

- name: "Check sops installed"
  shell: "sops --version | grep -qPe '^sops {{ sops_version }}.*'"
  register: version_check
  ignore_errors: True
  changed_when: False

- name: Install sops deb package
  ansible.builtin.apt:
    deb: "https://github.com/mozilla/sops/releases/download/v{{ sops_version }}/sops_{{ sops_version }}_amd64.deb"
    update_cache: False
  when: version_check is failed
