---

- name: "Check terraform is installed"
  shell: "terragrunt --version | grep -qPe '^terragrunt version v{{ terragrunt_version }}$'"
  register: version_check
  ignore_errors: True
  changed_when: false

- name: Download terragrunt binary
  get_url:
    url: "https://github.com/gruntwork-io/terragrunt/releases/download/v{{ terragrunt_version }}/terragrunt_linux_amd64"
    dest: "/usr/local/bin/terragrunt"
    force: yes
    owner: root
    group: root
    mode: 0755
  when: version_check is failed
