---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - libappindicator1
    - libindicator7
    - python-cairo
    - python-gobject-2
    - python-gtk2
    - openjdk-8-jdk
    - keepassx
    - geany
    - git
    - tig
    - vim
    - htop
    - mc
    - compizconfig-settings-manager
    - hipchat4
    - google-chrome-stable
    - docker-ce
    - virtualbox-5.2
    - python-pip

- name: Install vagrant package
  apt:
    deb: "https://releases.hashicorp.com/vagrant/2.0.2/vagrant_2.0.2_x86_64.deb"
    state: present

- name: Install Skype package
  apt:
    deb: "https://repo.skype.com/latest/skypeforlinux-64.deb"
    state: present

- name: install pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - awscli
    - aws-adfs
