---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - libappindicator1
    - libindicator7
    - python-cairo
    - python-gobject-2
    - python-gtk2
    - openjdk-8-jdk
    - keepassx
    - geany
    - git
    - tig
    - htop
    - mc
    - compizconfig-settings-manager
    - hipchat4
    - google-chrome-stable
    - docker-ce
    - virtualbox-5.2

- name: Install vagrant package
  apt:
    deb: "https://releases.hashicorp.com/vagrant/2.0.2/vagrant_2.0.2_x86_64.deb"
    state: present
