---
- name: Add Atlassian repository key
  apt_key:
    id: CC64091D
    url: https://atlassian.artifactoryonline.com/atlassian/api/gpg/key/public
    state: present

- name: Add hipchat repository
  apt_repository:
    repo: "deb https://atlassian.artifactoryonline.com/atlassian/hipchat-apt-client {{ ansible_distribution_release }} main"
    filename: atlassian-hipchat4

- name: Install packages
  apt:
    name: "hipchat4"
    state: latest
    update_cache: true
